apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: tardis
  labels:
    app: gitea
    app.kubernetes.io/part-of: tardis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
